### ISSUE TITLE
[CLN] TrackJudge CleanUp

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#102]
- [x] TrackAllResult Refactoring
- [x] Ajax 방식으로 할지 JSP의 JSTL을 사용할지 정하기

**Comment by riyenas0925** [comment]
![image](https://user-images.githubusercontent.com/32615702/69915285-a425ac80-1490-11ea-9683-506cf21b8819.png)
좌측은 JSTL을 이용해 빠르게 로딩 하고 왼쪽같은 경우 모든 트랙의 이수율을 계산해야 해서 시간이 오래걸리기 때문에 Ajax를 이용하여 나중에 받는 방식으로 변경

**Comment by riyenas0925** [comment]
@kimhanui 전체 이수율 보여주는 기능 jpa로 리펙토링 했는데 위와 같은 기능임 ㅇㅇ

**Comment by riyenas0925** [comment]
![image](https://user-images.githubusercontent.com/32615702/70058632-9a33b300-1622-11ea-8772-b8b0a1d2a04c.png)

**Comment by kimhanui** [comment]
이수율이 왜 111퍼로 뜨는거야? @riyenas0925

**Comment by riyenas0925** [comment]
@kimhanui 지금 6개 이수가 통과 기준인데 7개 이수 해서 그렇게 표시 되는거임 ㅇㅇ 이것도 원래 100 이상이면 100으로 되게 했었는데 우선 계산이 제대로 되는지 확인해볼라고 지금은 주석 처리 했으
