### ISSUE TITLE
궁금한 것 있다 - 공지사항 페이지

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#103]
## home.jsp
![image](https://user-images.githubusercontent.com/30483337/69916039-37fb7680-1499-11ea-878b-3b1e5c8d987a.png)

공지사항 href 경로가 /home로 돼있는건 아직 공지사항 페이지를 안 만들어서 더미값 넣은건가?? @riyenas0925 @2kyung19

**Comment by riyenas0925** [comment]
@kimhanui 정답이다 이말이야~
