### ISSUE TITLE
[BUG] trackRule.jsp에서 심화교과 설정박스가 popup 밖으로 나오는 오류

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#105]
![image](https://user-images.githubusercontent.com/30483337/69935355-f3fb8680-1517-11ea-9625-8352de87dbdf.png)

심화교과 옆에 학점 설정하는거 하나 더 생김. 산학연계 때문에 하나 더 만든건가?
@riyenas0925

**Comment by riyenas0925** [comment]
@kimhanui 이것도 정답이고 아직 trackRule은 jpa로 변경하면서 삭제기능 빼고는 작동 안할거여

**Comment by kimhanui** [comment]
@riyenas0925 삭제기능 빼고? 그럼 추가랑 변경은 아직 구현안한거고 나중엔 구현하는거지?

**Comment by riyenas0925** [comment]
@kimhanui 아 구현이 안된건 아니고 구현은 되어있는데 mybatis에서 jpa로 변경하면서 수정해야할게 몇가지 있어서 이것만 하면 잘 작동함 ㅇㅇ

**Comment by riyenas0925** [comment]
@kimhanui 요거 언젠가는 해결해야할 버그라 다시 Reopen 할께
