### ISSUE TITLE
[BUG] 트랙통계관리 side메뉴 접었을 때 디자인버그

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#111]
## 증상
* 스샷 잘 보면 저게 `트랙 통계 관리` 부분인데 마우스 안 올려도 글씨가 노출되어있음  
* 마우스 올려서 스샷찍는걸 못해서 일케 밖에 못올렷으나 실제로 마우스 올려보면   
다른 메뉴부분이랑 조금 다르게 생김
@riyenas0925 임시용으로 만든건가?

## screenshot
![image](https://user-images.githubusercontent.com/30483337/70388503-07b25b80-19f6-11ea-953a-278129e3855b.png)

## response
```json
```

## server log
```
```

## 실행 환경
 - OS: window10 Home
 - Browser: chrome

**Comment by riyenas0925** [comment]
@kimhanui 사이드 메뉴를 접으면 저런 오류가 뜨는건가??  크롬 개발자 모드 콘솔 들어가서 에러 뜨나 한번 확인 부탁~

**Comment by kimhanui** [comment]
@riyenas0925 ㄴㄴ 에러는 안뜸    
이런식으로 뜸
![image](https://user-images.githubusercontent.com/30483337/70389875-992ac900-1a08-11ea-928f-640e2178e885.png)

**Comment by riyenas0925** [comment]
@kimhanui 엥 이건 확인해봐야 겠네

**Comment by riyenas0925** [comment]
@kimhanui 새로운 PR 올렸고 사이드바에 tree를 지원을 안하는것 같음.... 그래서 삭제 하고 나중에 Graph 기능 만들때 생각해보자
