### ISSUE TITLE
[BUG] MemberRole의 insert쿼리문 에러 (data.sql)

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#116]
## 증상
```javascript
INSERT INTO tbl_member_role(roleId,role_enum, memberId) VALUES (1,role_enum.'STUDENT', "student");
INSERT INTO tbl_member_role(roleId,role_enum, memberId) VALUES (2,role_enum.'PRO', "pro");
INSERT INTO tbl_member_role(roleId,role_enum, memberId) VALUES (3,role_enum.'ADMIN', "admin");
```
data.sql에 이런식으로 쿼리문 작성하면 에러발생

issue from > https://github.com/riyenas0925/Project-Sejong-Track-Management/pull/104#issuecomment-565013388
## 시나리오
- 멤버테이블이랑 연관관계 문젠가
- @GeneratedValue(strategy = GenerationType.IDENTITY)으로 설정한 roleId의 쿼리문 넣을 때 저렇게 1,2,3,, 이런식으로 넣으면 안되는 것인가? --> _**이거에 대해 뭔가 알면 조언좀**_ @riyenas0925 
## response
```json
```

## server log
```
```

## 실행 환경
 - OS: window10 home
 - Browser: chrome

**Comment by riyenas0925** [comment]
#### 확인한 에러

* jsp 단에서 hasRole이 적용인 안되는 오류 발생
```jsp
<sec:authorize access="hasRole('admin')">
    <br>안녕하세요 관리자님
</sec:authorize>
```
* jsp 부분은 조금 수정이 필요할듯??
Google 로그인, faceBook 로그인 adminLTE에 맞지않는 양식 등등.....

* ```</br>```은 없다 이말이야~   

![image](https://user-images.githubusercontent.com/32615702/70720775-cb556700-1d37-11ea-916a-d608bb6ef45c.png)

tbl_member_role은 아래와 같이 변경하면 해결
```sql
INSERT INTO tbl_member_role(role_enum, memberId) VALUES ("STUDENT", "student");
INSERT INTO tbl_member_role(role_enum, memberId) VALUES ("PRO", "pro");
INSERT INTO tbl_member_role(role_enum, memberId) VALUES ("ADMIN", "admin");
```

**Comment by riyenas0925** [comment]
@kimhanui 그리고 기본 아이디, 비밀번호 student,pro,admin은 어떤 코드에서 생성하는거야...? 전부 찾아봤는데 어디서 생성하는지 못찾겠음.....

**Comment by kimhanui** [comment]
> #### 확인한 에러
> * jsp 단에서 hasRole이 적용인 안되는 오류 발생
> 
> ```
> <sec:authorize access="hasRole('admin')">
>     <br>안녕하세요 관리자님
> </sec:authorize>
> ```
> 
> * jsp 부분은 조금 수정이 필요할듯??
> 
> tbl_member_role은 아래와 같이 변경하면 해결
> 
> ```sql
> INSERT INTO tbl_member_role(role_enum, memberId) VALUES ("STUDENT", "student");
> INSERT INTO tbl_member_role(role_enum, memberId) VALUES ("PRO", "pro");
> INSERT INTO tbl_member_role(role_enum, memberId) VALUES ("ADMIN", "admin");
> ```

아아 그부분 hasRole이 아니라 우린 hasAuthority로 바꿔야 돼서 다음 pr에 바꿔서 올릴게

**Comment by riyenas0925** [comment]
@kimhanui ㅇㅎㅇㅎ 찾아낸 오류 추가해서 수정했으니까 위에 다시한번 봐주라

**Comment by kimhanui** [comment]
> @kimhanui 그리고 기본 아이디, 비밀번호 student,pro,admin은 어떤 코드에서 생성하는거야...? 전부 찾아봤는데 어디서 생성하는지 못찾겠음.....

data.sql에 넣었는디? 이거 물어본게 아닌가?
![image](https://user-images.githubusercontent.com/30483337/70720940-1d968800-1d38-11ea-8000-af8bbba24241.png)

**Comment by kimhanui** [comment]
@riyenas0925

- [x] 요렇게 바꿧다리
![image](https://user-images.githubusercontent.com/30483337/70721048-4d459000-1d38-11ea-9cd5-1787cf4aeeba.png)

- [x] Google 로그인, faceBook 로그인 : 이건 그냥 ui만 있는데 어차피 안쓸꺼면 뺄까?

**Comment by kimhanui** [comment]
> tbl_member_role은 아래와 같이 변경하면 해결
> 
> ```sql
> INSERT INTO tbl_member_role(role_enum, memberId) VALUES ("STUDENT", "student");
> INSERT INTO tbl_member_role(role_enum, memberId) VALUES ("PRO", "pro");
> INSERT INTO tbl_member_role(role_enum, memberId) VALUES ("ADMIN", "admin");
> ```
# Solved ✔️

**Comment by riyenas0925** [comment]
@kimhanui 아 맞네 data.sql에 있었네 나는 스프링 설정에서 정해준다고만 생각해서 그것만 찾음 ㅋㅋㅋ

**Comment by kimhanui** [comment]
> @riyenas0925
> 
> * [x]  요렇게 바꿧다리
>   ![image](https://user-images.githubusercontent.com/30483337/70721048-4d459000-1d38-11ea-9cd5-1787cf4aeeba.png)
> * [x]  Google 로그인, faceBook 로그인 : 이건 그냥 ui만 있는데 어차피 안쓸꺼면 뺄까?

@riyenas0925 굳굳ㅋㅋ 이것도 확인해주라

**Comment by riyenas0925** [comment]
@kimhanui ㅇㅇ 지금보면 양식에 안맞는 jsp들 있자너??? 예를들면 헤더에 로그인 전에도 로그인 된것 처럼 오른쪽에 게스트가 떠있고 회원가입에서 admilte가 적용안되있는 버튼이나 체크박스 이런부분들 adminlte로 적용해줬으면 좋겠어 그리고 게스트 부분은 로그안한 멤버 정보로 나오게 해줄수 있나???
