### ISSUE TITLE
[CLN] Spring Boot 파일 구조 변경 

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#122]
# Spring Boot 파일 구조 변경
@kimhanui  지금 프로젝트를 보니까 너무 많은 폴더가 있고 뭔가 기능 별로 구분이 안되는 느낌이여서 아래와 같이 변경하려고 하는데 어떰?

#### 현재 파일 구조
```
└sejong
    ├─config
    ├─controller
    ├─domain
        └─Entiry
    ├─dto
    ├─handler
    ├─listener
    ├─persistence 
    ├─persistence_old
    └─service
```
#### 수정예정인 파일 구조
```
└sejong
    ├─config
    ├─web(이전 controller)
        └─dto
    ├─domain
        └─ Repository (이전 persistence)
        └─ Entity
    ├─handler
    ├─listener (어디에 포함?)
    └─service (어디에 포함?)
```

### 변경 이유 
* dto는 Web Layer와 Service Layer에 걸쳐있는 Layer 이기 때문에 web 안에 넣는게 좋다고  생각함
* Entity과 Repository는 밀접한 관련이 있기 떄문에 지금과 같이 따로 분리하는 것보다 각각 도메인으로 패키지를 만든다음 그안에 Entiry와 Repository를 넣는것이 좋다고 생각함

### 추가적으로 의논해봐야 할 사항
그러면 handler와 listener는 어디에.......?

**Comment by kimhanui** [comment]
@riyenas0925 음 혹시 디자인 패턴이랑 연관있는 파일 구조임?

**Comment by riyenas0925** [comment]
@kimhanui 디자인 패턴은 아니고 Spring 웹 계층을 따져보면 저렇게 하는게 더 괜찮은것 같아서
전에 winter project 할때도 수정예정중인 파일 구조에 조금 더 가깝더라고

![image](https://user-images.githubusercontent.com/32615702/73608996-aaf5aa80-460c-11ea-8321-216b32424df9.png)

**Comment by riyenas0925** [comment]
만약 변경된다면 지금 진행하고 있는 회원 정보 수정 기능 끝나고 할까 함 ㅇㅇ

**Comment by riyenas0925** [comment]
@kimhanui 

핸들러와 리스너도 아래와 같이 web에 넣으면 되겠다
```
└sejong
    ├─config
    ├─web(이전 controller)
        ├─dto
        ├─handler
        └─listener
    ├─domain
        └─ Repository (이전 persistence)
        └─ Entity
    └─service
```

**Comment by kimhanui** [comment]
@riyenas0925 ㅇㅋㅇㅋ 회원정보 수정 끝내고 파일구조 변경하자
