### ISSUE TITLE
[ENH] new bootstrap template

### ISSUE THREAD

**Issue by 2kyung19** [riyenas0925/Sejong_Track_Management#131]
@riyenas0925 @kimhanui 
### default
![image](https://user-images.githubusercontent.com/32586712/73814578-d94ed200-4826-11ea-96d1-9ef32ab4bdba.png)
이 안에서 지지고 자시고 할 듯 , sidebar에서 목록 확인하세용

### 페이지
- [x] default page ( home )
- [x] 로그인
- [x] 회원가입
- [ ] 정보수정
- [x] 404 page
- [ ] 강의시간표 추가
- [ ] 전체 트랙 조회
- [ ] 트랙 현황 조회
- [ ] 공지사항
- [ ] main page 마무리

++ 더 추가할꺼 있나?

**Comment by kimhanui** [comment]
@2kyung19 

+ 예쁜 404 페이지요(expired.jsp, denied.jsp)

+ pw_popup.jsp-이건 비밀번호 수정용 팝업창

세개 다 파일구조 보면 member/ 밑에 있음

**Comment by riyenas0925** [comment]
@2kyung19 굿굿 그럼 자금 jsp로 개발하고 있는건가??

**Comment by riyenas0925** [comment]
@2kyung19 굿굿 그럼 지금 jsp로 개발하고 있는건가??

**Comment by 2kyung19** [comment]
@riyenas0925 default 페이지만 jsp로 해놓은 상태
adminLTE했던거랑 똑같이
sidebar/setting(title이나 link같은...태그)/footer/header
include이용해서 블럭 처리 하는 것만 했슴다
낼 로그인 시도해 볼 예정

**Comment by riyenas0925** [comment]
@2kyung19 ㅇㅎㅇㅎ 그럼 전환 완료하면 adminLTE는 삭제하는걸로 하자

**Comment by 2kyung19** [comment]
## 20200206 보고
* adminLTE 적용했던 jsp 파일들 이름 그대로 따서 하고있습니다. 컨트롤러 따로 안 만져도 됩니다.
* 주소할당 다 적용해서 그냥 바로 넣었습니다. 혹시 PR원하면 올리겠슴다.

## 임시 홈
* home.jsp
![image](https://user-images.githubusercontent.com/32586712/73911846-5c8b2900-48f6-11ea-9a67-4db2c02114a5.png)

<b>+ 메인컨텐츠는 대시보드 그대로 가져옴 나중에 아이디어 내면 추가</b>

## 에러 페이지
* denied.jsp
![image](https://user-images.githubusercontent.com/32586712/73911787-31a0d500-48f6-11ea-80ad-47af804941c3.png)
* expired.jsp
![image](https://user-images.githubusercontent.com/32586712/73911724-06b68100-48f6-11ea-9012-6456fa9c8fdd.png)

<b> +무려 물결 움직인다규!!</b>
![녹화_2020_02_06_15_59_09_728](https://user-images.githubusercontent.com/32586712/73913184-b7724f80-48f9-11ea-92de-d0fb504d779e.gif)

## 로그인
* loginView.jsp
![image](https://user-images.githubusercontent.com/32586712/73911968-a411b500-48f6-11ea-945d-c85854833b4a.png)

## 건들지말아줬으면 하는 파일 (머지 충돌 예방)
* homecontroller > 임시로 주소 할당해서 테스트용으로 쓰고있습니다.
* web-inf에 있는 모든 jsp 파일 > 뭐 만질꺼같으면 알려주세요.
* resources에 있는 모든 파일 > 추가하고 삭제하고 난리남.

**Comment by 2kyung19** [comment]
@kimhanui 
## 회원가입
* joinView.jsp
![image](https://user-images.githubusercontent.com/32586712/73921090-1213a780-490a-11ea-99b0-458212c3cfb8.png)

아이거진짜 억울해죽겠네

**Comment by riyenas0925** [comment]
@2kyung19 와 디자인 너무 맘에드는데 진짜 깔끔하네 잘 만들었네

**Comment by 2kyung19** [comment]
> @2kyung19 와 디자인 너무 맘에드는데 진짜 깔끔하네 잘 만들었네

부트스트랩 테마 만세만세만만세

**Comment by riyenas0925** [comment]
@2kyung19  아그러고 기능 별로 브랜치 만들어서 하고 있는거지 ?

**Comment by 2kyung19** [comment]
@riyenas0925 기능이 저 템플릿 교체밖에없어서,,,, 그냥 포크떠가지고 develop 브랜치 만들어서 master랑 머지시키고 그러고있는데.....................문제되나유...? 업스트림 설정 해놓음ㅇㅇ

**Comment by riyenas0925** [comment]
@2kyung19 앗아.... 설마 feature 브렌치 안만들고 한건 아니지???

**Comment by 2kyung19** [comment]
@riyenas0925 
포크 뜬 레포지토리 인데 브랜치 상관없지않아?
아니 계속 feature 브랜치에서 작업하고있었는데
확인해보니까 내가 로컬 master 브랜치랑
업스트림 develop이랑 연결시켜놨더라공....
내 로컬 develop이 걍 master복붙이던데
굳이 귀찮게 건너서 쓸필요없어서 feature, develop에 머지시키고 feature 쓰듯이 쓰고있는데

**Comment by 2kyung19** [comment]
# 로그인 끝난 듯?
* 추가 피드백 받고 수정 후 이슈 클로즈하겠슴다

## 정보수정
* web
![image](https://user-images.githubusercontent.com/32586712/74103606-bdce2900-4b90-11ea-8ca4-f8392a4c757d.png)

* tab/mobile
![image](https://user-images.githubusercontent.com/32586712/74103633-1e5d6600-4b91-11ea-8edd-7b50865075df.png)
> 밑부분 캡챠 귀찮

## 비밀번호변경 modal
![image](https://user-images.githubusercontent.com/32586712/74103656-44830600-4b91-11ea-821c-73af098c8294.png)

**Comment by 2kyung19** [comment]
그 정보수정쪽에서 id빼고 readonly해놓은건 걍 임의로 때린거라 막아놨어여

**Comment by riyenas0925** [comment]
@2kyung19 와..... 디자인 먼데 진짜 잘만들었네 :+1: :+1: 
아 글고 TrackSubject 이슈 하나 올렸으니까 참고~ #132

**Comment by riyenas0925** [comment]
@2kyung19  아 그리고 나중에 PR 올릴때 커밋 메시지를 아래처럼 입력하면 pr과 동시에 이 이슈도 닫힘 ㅇㅇ
```
ENH : 커밋 어쩌구 저쩌구
Resolves #131 
```

**Comment by riyenas0925** [comment]
@2kyung19, @kimhanui 엥 권한 설정 건드리다가 콜라보 인원 다 날라갔네;;; 다시 이메일로 초대 받으시면 됩니다~
