### ISSUE TITLE
[ENH] TrackSubject 페이지 디자인

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#132]
@2kyung19 이제부터 디자인도 기능당 이슈 하나씩 만들어서 작업하자
- [x] TrackSubject 페이지 디자인

**Comment by riyenas0925** [comment]
@kimhanui 나중에 api 같은것 문서화 생각하면 아래처럼 간단하게라도 명세서를 만드는게 좋을것 같은데 어떻게 생각함??
@2kyung19 이거 보고 한번 만들어 보면 될듯

![image](https://user-images.githubusercontent.com/32615702/74103288-4d260d00-4b8e-11ea-8ac4-5601a6c088e3.png)

### ajax 요청 url
#### 기본 url : /api/v1/admin/courseSchedule/*

#### 강의시간표 추가 (form 태그와, submit 태그)
* save
    > Post : MultipartFile file
    1. 강의시간표 엑셀의 이름으로 CourseSchedule 테이블에 추가하고, 그 항목을 외래키로 엑셀 파일 안에 있는 과목들을 Subject에 추가한다.
    2. 강의시간표 안에있는 중복 내용은 삭제하는 기능 구현

#### 강의시간표 삭제
* delete/{id}
    > Delete : Long id
    1. 강의시간표 삭제 기능
    2. 강의시간표를 삭제하면 속한 과목도 전부 삭제된다.

#### 강의시간표 목록
* list
    > Get : void
    1. 강의 시간표 전체 목록
    2. CourseSchedule과 Subject테이블이 연관관계이기 때문에 강의시간표 안에 속한 과목까지 전부 표시됨

* list/{id}
    > Get : Long id
    1. 강의시간표 검색 목록
    2. 강의시간표 하나만 검색해 표시, 나오는 방식은 list-2 번과 동일하게 전부다 출력

#### Select 박스용 목록
* select
    > Get : void
    1. 위에 구현한 list가 강의시간표에 속한 과목까지 표시하기 때문에 필요한 CourseSchedule만 출력할수 있게 구현

**Comment by riyenas0925** [comment]
@2kyung19 음 그리고 추가적으로 몇가지 기능 생각해봤는데
1. 파일 첨부시 팝업으로 간단하게 파일 내용을 보여주고, Multiselect를 이용하여 원하는 학과의 과목만 선택해서 첨부하는 기능(아마 위에 Info를 누르면 보여주게 설계하면 될것 같음)
2. 디자인 한거 보면 강의시간표 선택이 multiselect로 되어있는데 우선 select나, 아니면 체크박스 하나만 선택할수 있게 구현하는 방식으로 하자 여러개 선택하는거는 어떻게 할지 생각해봐야 할것 같아서
3. Subject CRUD...? 이것도 생각해봤는데 굳이 강의시간표 첨부하는 페이지에서 구현해야하나 싶어서 #97 여기 대학, 트랙, 과목 설정하는 페이지에서 하는게 좋을것 같음

**Comment by riyenas0925** [comment]
@2kyung19 그리고 ajax로 처리하는 걸로 하고, 되도록이면 jsp에서 로직이 안들어가게 하자

**Comment by 2kyung19** [comment]
갑자기 확 현타온다

**Comment by 2kyung19** [comment]
@riyenas0925 
생각해봤는데 강의시간표 저 셀렉트 필요없을꺼같지않냐
어차피 밑에 과목 테이블에서 년도/학기 다 저장해서 나와있으니까

* 강의시간표 추가하는 이유가 나중에 트랙 수정/추가할 때, 과목 지정
편리하게 하기위해서잖어, 그럼 여기는 기능 많이 추가안해도 괜찮을꺼같아
* 트랙 수정/추가가 헬이지 여기는 그냥 단순한 업로드용?

>파일 첨부시 팝업으로 간단하게 파일 내용을 보여주고,   

이건 완전 좋아

>Multiselect를 이용하여 원하는 학과의 과목만 선택해서 첨부하는 기능(아마 위에 Info를 누르면 보여주게 설계하면 될것 같음)  

이거는 잘모르겠다

**Comment by 2kyung19** [comment]
@riyenas0925 
굳이 기능을 넣는다고하면 강의시간표 db 초기화?

**Comment by 2kyung19** [comment]
@riyenas0925 아주 살짝 바꿨어
약간 강의시간표 업로드 관련 기능 들은 modal로 넘기는게 깔끔할꺼같아

저 밑에 과목 테이블은 그냥 반영되어있는거 전체로 보여주는게 나을꺼같아서
강의시간표 select부분 없앴다.

그 대신 이미 업로드되어있는 강의시간표 조회/삭제 기능은 버튼눌러서 modal 띄우고 거기서 처리

## static page
* url (/trackSubject)
![image](https://user-images.githubusercontent.com/32586712/74314806-77a7de00-4db9-11ea-99b7-5c1d77f46458.png)
> 밑에 과목테이블 쓰레기값 넣어논거

* 업로드 부분
![image](https://user-images.githubusercontent.com/32586712/74314892-a4f48c00-4db9-11ea-871b-72829470c602.png)

### button 들은 시간표 추가 빼고 모두 modal 적용예정
* subject/help.jsp : 주의사항같은 것들
* subject/list.jsp : 여태까지 적용된 강의시간표 목록 조회 / 제거
* subject/preview.jsp : 지금 form에 input한 파일 table로 미리보기

### 한눈에보기
* default
![image](https://user-images.githubusercontent.com/32586712/74316325-b0958200-4dbc-11ea-839b-6ebc9ecefef8.png)
* success
![image](https://user-images.githubusercontent.com/32586712/74316399-cefb7d80-4dbc-11ea-8138-fed3fdf398e7.png)
* fail
![image](https://user-images.githubusercontent.com/32586712/74316437-dde23000-4dbc-11ea-8dc5-d7f89560a30b.png)

----
우선 이렇게 했는데,,,음.... 강의시간표 엑셀파일 어떻게 받는지모른다맨  
피드백받고 이어서 modal 만들건데 강의시간표 저거 엑셀파일 어디서구해야되는거야

**Comment by riyenas0925** [comment]
@2kyung19 아 강의시간표 엑셀 파일은 여기서 [세종대학교 공지사항 학사](http://board.sejong.ac.kr/boardview.do?pkid=121345&currentPage=2&searchField=ALL&siteGubun=19&menuGubun=1&bbsConfigFK=335&searchLowItem=ALL&searchValue=) 엑셀파일 다운받아서 사용하면되고
그리고 select부분은 나도 만들면서 굳이 필요할까라는 생각이 들기는 했었음 지금보니까 없애는게 더 깔끔한것 같네

**Comment by 2kyung19** [comment]
## list 출력
![image](https://user-images.githubusercontent.com/32586712/74339049-a5574c00-4de6-11ea-8e93-c1c3b596b387.png)

## search
![image](https://user-images.githubusercontent.com/32586712/74339154-d5065400-4de6-11ea-89d1-dd09eb45cc65.png)
> 아직 table 너비 고정 해야하긴하지만 나중에합시댜

**Comment by riyenas0925** [comment]
@2kyung19 오 뭐야 검색 기능 프론트 단에서 구현한건가??

**Comment by 2kyung19** [comment]
@riyenas0925 엉 근데 너비가 좀 불안정해서 고정시키기만 하면 될꺼같음

**Comment by riyenas0925** [comment]
@2kyung19 ㅇㅎㅇㅎ 그러면 이대로 pr 올려주라

**Comment by 2kyung19** [comment]
@riyenas0925 옹? 잠만
![image](https://user-images.githubusercontent.com/32586712/74343231-16e6c880-4dee-11ea-96f2-09b6c6af1c84.png)
이거 삭제기능은 아직 x 지금올릴께

**Comment by 2kyung19** [comment]
@riyenas0925 @kimhanui 
ajax delete부분 안봐주면 파업할꺼임

**Comment by 2kyung19** [comment]
## file delete
![image](https://user-images.githubusercontent.com/32586712/74600153-a29f7400-50d0-11ea-8cc7-c3f6c10df93d.png)

## loading img
![image](https://user-images.githubusercontent.com/32586712/74600309-01fe8380-50d3-11ea-8877-51356976d15f.png)

## 해야되는거

- [ ] file upload 후 시간표 추가 > ajax url들어갔다가 안돌아옴
- [ ] delete id 순서 뒤집어서 삭제하면 이상하게됨 확인요망
- [ ] 도움말 modal
- [ ] 미리보기 modal (이건 구현 가능한지 잘 모르겠음 일단 보류)

**Comment by riyenas0925** [comment]
@2kyung19 지금 오류 나는지 확인해보고 있는데 코드 상으로는 역순으로 제거해도 문제 없는데 혹시 어떤 오류 나는지 알려줄수 있음?
