### ISSUE TITLE
[help] 자원 경로

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#152]
## 템플릿 변경하면서 자원 추가됨.
![image](https://user-images.githubusercontent.com/30483337/75221779-fce1b880-57e5-11ea-9b35-1524ce27a858.png)

## 그러나 StaticResourceConfig의 경로는 그대로임. 경로 추가할 필요 없는가?
![image](https://user-images.githubusercontent.com/30483337/75221761-f05d6000-57e5-11ea-8b0c-06b4eef6f282.png)

@riyenas0925

**Comment by riyenas0925** [comment]
@kimhanui 외부 리소스 폴더를 사용하고 절대경로로 import 하려고 환경에 추가한건데, 이번에 추가한 리소스 들은 저기에 추가를 안해도 작동하는건가...? 이거는 @2kyung19 한테 한번 물어봐바

**Comment by 2kyung19** [comment]
추가로안해도 작동되게 경로해놔서그런가..? 저건 나중에 jsp 다 만들어지면 자원들 지울 예정

+ @kimhanui 말투 한국말 서툰 외국인같음ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by riyenas0925** [comment]
@2kyung19 ㅇㅎㅇㅎ 그럼 전에 있던 전에있던 dist, bower_component, plugins 빼고는 너가 추가 한건가??
@kimhanui ㅋㅋㅋㅋㅋㅋ 말투 뭐여

**Comment by 2kyung19** [comment]
넴넴 이번 부트테마 임다

**Comment by riyenas0925** [comment]
@2kyung19 AdminLTE에서 Argon이라는 부트스트랩 템플릿으로 변경한거가 맞지? 내가 이해 한게 맞나

**Comment by 2kyung19** [comment]
네 맞아요

**Comment by kimhanui** [comment]
고맙다 이놈들아^^

spring security에서 자원경로때매 권한문제에 안 충돌하려면 여기서만 설정해두면 되나? 

경로 이렇게 해두면 충돌은 없음. 그런데 저 경로가 올바른 방식인가? @riyenas0925
![image](https://user-images.githubusercontent.com/30483337/75222867-898d7600-57e8-11ea-8b1a-f4b75b110284.png)

**Comment by riyenas0925** [comment]
@kimhanui 음... 맞는지는 확인해봐야 할것 같은데 지금 잘 작동하고 있는거 보니까 맞는듯....?

**Comment by riyenas0925** [comment]
@2kyung19 , @kimhanui 지금 다들 시간 괜찮으면 회의 가능하십니까요?

**Comment by kimhanui** [comment]
@riyenas0925 맞게 잘 쓴듯? (spring boot ant matchers pattern임 참고.)
https://lng1982.tistory.com/169

**Comment by riyenas0925** [comment]
@kimhanui @2kyung19 아닠ㅋㅋ 가능하다는거지?
