### ISSUE TITLE
[ENH] : trackAll 페이지 디자인

### ISSUE THREAD

**Issue by 2kyung19** [riyenas0925/Sejong_Track_Management#155]
![image](https://user-images.githubusercontent.com/32586712/75791922-a01b6a80-5db0-11ea-96a9-0adf35dc7e0e.png)

기존 전체트랙보기 형식이 기초교과나 응용교과를 하나하나 보기 어렵다고 해서 바꿔봤슴다 기존에 한눈에 보는 테이블이 좋으면 그걸로 시작할께요

* 학수번호 툴팁은 나아아아아아ㅏㅏㅏ중에 구현해도됨 (구현안해도ㅇㅇ)
* 지금 trackAll/1로가도 아무런 데이터 없는게 당연한거지..?ㅜㅠ
jsp에서 trackBasic / trackApplied 얘네가 어떤식으로 출력되는지 모르겠네 콤마로 구분지은 스트링이였나?   
"선형대수및프로그래밍,멀티미디어" 이런식으로

**Comment by riyenas0925** [comment]
@2kyung19  api/v1/trackAll/1 이걸로 접속 해봐바, 전에는 콤마로 구분된 String이였음 ㅇㅇ

**Comment by 2kyung19** [comment]
@riyenas0925 @kimhanui 피드백 원해요 특히 테이블 부분 지금 글자 너무 작나 안 보일 정도는 아니고 조금 작은 편 (교과목 명 길이가 길어서)

## 전체 트랙 보기
![image](https://user-images.githubusercontent.com/32586712/75883775-e29f7e80-5e66-11ea-8c24-8b6f8ec1c173.png)
< default 화면 >

![image](https://user-images.githubusercontent.com/32586712/75883374-3f4e6980-5e66-11ea-846c-cb537dc943c4.png)
< select 화면 >
* 교과목 부분은 나중에 너비나 길이 조정해야 할 듯

## 주요 코드 (나중에 pr올라가면 코드 참고 하면서 보세여)
>> 나중에 내가 헷갈릴꺼같아서 적어놓음요ㅠ
#### thead (기초/응용 등등 목록 가져오기)
* data : api/v1/trackAll/{univId} 에서 가져온 json
![image](https://user-images.githubusercontent.com/32586712/75885294-9f92da80-5e69-11ea-908c-0304d6bc6578.png)

#### track name (트랙 이름 가져오기)
* data : api/v1/trackAll/{univId} 에서 가져온 json
* 다른 함수들에서 계산한 값도 return 받아 한번에 table에 넣는 함수
* <tr> 트랙명 + jsonArray에서 과목 추출 하여 str로 반환받음 </tr>
![image](https://user-images.githubusercontent.com/32586712/75888065-1f22a880-5e6e-11ea-8178-97d5883fa157.png)



### jsonArray (과목 가져오기)
* data : 과목 정보들어있는 list
* 목록마다 실행함
* ex)기초 : 함수 한 번 실행
  ex) 기초,응용: 함수 두 번 실행
![image](https://user-images.githubusercontent.com/32586712/75887301-efbf6c00-5e6c-11ea-8f3b-8bb235a63e51.png)

json data 가공 한번도 안해봐서 이렇게 하는게 맞는지 모르겠는데
더 효율적인 방법 있으면 알려주세욘

**Comment by kimhanui** [comment]
> ![image](https://user-images.githubusercontent.com/32586712/75791922-a01b6a80-5db0-11ea-96a9-0adf35dc7e0e.png)
> 
> 기존 전체트랙보기 형식이 기초교과나 응용교과를 하나하나 보기 어렵다고 해서 바꿔봤슴다 기존에 한눈에 보는 테이블이 좋으면 그걸로 시작할께요
> 
> * 학수번호 툴팁은 나아아아아아ㅏㅏㅏ중에 구현해도됨 (구현안해도ㅇㅇ)
> * 지금 trackAll/1로가도 아무런 데이터 없는게 당연한거지..?ㅜㅠ
>   jsp에서 trackBasic / trackApplied 얘네가 어떤식으로 출력되는지 모르겠네 콤마로 구분지은 스트링이였나?
>   "선형대수및프로그래밍,멀티미디어" 이런식으로

+ 와 나 왜 이거 지금봣지 이거 ui되게 괜찮다 표 보다 좋은것같은디..? 왜 표로 가게 된거야?
+ 글자 크기 조금 작지만 ㄱㅊㄱㅊ 근데 그 크기에서 더 줄이면 읽기 불편할것같음 ㅇㅇ
+ 제안) 혹시 지금 표에서 교과목들 나열하는걸 한 줄 내로 하고싶어서 글자크기 줄인거라면 트랙마다 드랍다운 형태로 만들어서 영역을 더 확보하는건 어때?
@2kyung19

**Comment by 2kyung19** [comment]
@kimhanui 위 형태 저거 괜춘한데 
모바일 이용자가 한 눈에 보기 좀 어려울 수 있다는 문제점 발생
배치는 언제든 변경할 수 있으니 우선 전체 테이블로 ㄱㄱ 가 되었다

>드롭다운도 좋은거같아 ㅇㅇㅇㅇ 근데 모바일에선 배치가 괜찮은데 웹에서는 애매할꺼같아서 일단  그것도 보류ㅠㅠ

위 배치 : 웹에선 ㄱㅊ 모바일 ㄴㄴ
드롭다운 : 웹에선 애매 모바일 짱좋
ㅠㅜㅜㅜㅠㅜㅠㅜㅠ

**Comment by riyenas0925** [comment]
@2kyung19 깔끔하네 표 방식 같은경우는 추후에 의논해서 하는걸로 하자
우선 이걸로 pr 올려주라

**Comment by 2kyung19** [comment]
나아아ㅏㅏㅏㅏ중에 (그럴일없겠지만) 웹:위배치 모바일:드롭다운 시도하지않지않지않지않지않지않
