### ISSUE TITLE
[DOC] api url 정리

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#163]
## 공통
- base url : `localhost:8080`
- method + api url + 송/수신 json타입 정리 

## url 정리
- member
```javascript
비밀번호 변경 : /api/v1/member/modifyPw [Post]
    - json to server : {String id, String password, String newPw}
    - json to client : - 
```

**Comment by kimhanui** [comment]
@riyenas0925 뭔가 보기 불편한 것 같기도? 일단 이렇게 적어놓게슴

**Comment by riyenas0925** [comment]
@kimhanui 아니면 테이블로 변경할까?

**Comment by kimhanui** [comment]
> @kimhanui 아니면 테이블로 변경할까?

@riyenas0925 아 ㅇㅇ 테이블 ㄱㅊ한듯?

**Comment by riyenas0925** [comment]
@kimhanui swagger 사용해서 정리하는 걸로 하자
