### ISSUE TITLE
[ENH] @Controller 통합

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#165]
@kimhanui  @Controller에서 Index, TrackJudge, Auth 이렇게 3가지로 구분하면 충분할것 같아서 오늘 수정해서 올릴께

**Comment by riyenas0925** [comment]
@kimhanui 구분은 Index(일반적인 페이지), Auth(로그인, 로그아웃 등등.....), TrackJudge(트랙 판정 관련 페이지) 이렇게 3개로 나누는 거는 어떻게 생각함??

**Comment by kimhanui** [comment]
@riyenas0925 그럼 notice는 어디 들어감?

**Comment by riyenas0925** [comment]
@kimhanui 음 이거는 IndexController 들어가면 될것 같은데??

**Comment by kimhanui** [comment]
@riyenas0925 아 noticeApiController도??

**Comment by riyenas0925** [comment]
@kimhanui 아아 api 컨트롤러는 따로 합치지 말고 api컨트롤러 + Index, Auth, TrackJudge... 이렇게 말한거였음 ㅋㅋ

**Comment by kimhanui** [comment]
@riyenas0925 아 오키오키 ㅋㅋ

**Comment by riyenas0925** [comment]
@kimhanui 이거 내가 해서 PR 올렸슴다
