### ISSUE TITLE
[BUG] 빈 순환참조 오류

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#166]
## 증상(로그)
```
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  springSecurityConfig defined in file [D:\Github\Sejong-track-2019\Project-Sejong-Track-Management\target\classes\kr\ac\sejong\config\SpringSecurityConfig.class]
↑     ↓
|  authProvider defined in file [D:\Github\Sejong-track-2019\Project-Sejong-Track-Management\target\classes\kr\ac\sejong\service\CustomAuthenticationProvider.class]
↑     ↓
|  customUserDetailsService defined in file [D:\Github\Sejong-track-2019\Project-Sejong-Track-Management\target\classes\kr\ac\sejong\service\CustomUserDetailsService.class]
└─────┘



Process finished with exit code 0

```

## 원인
의존관계
```
SpringSecurityConfig  -> authProvider -> customUserDetailsService
          ↖    ←    ←    passwordEncoder  ←    ←      ↙
```
- 생성자 주입(private final) 쓰면  생성과동시에 빈등록 하므로 애플리케이션 구동시에 빈 순환참조 오류를 잡아낼 수 있다.
(지금까지는 @Inject 를 써서 몰랐던 것 같다).

## 일단 임시조치로 @Inject를 쓰고 나중에 재설계 하기로 함.

> 해결방안
> - [인터페이스 만들어서 참조](https://joycoding.wordpress.com/2016/02/05/%EC%88%9C%ED%99%98%EC%B0%B8%EC%A1%B0-%EB%81%8A%EC%9E%90-breaking-dependency-circle/)
> - [하향식 설계](http://redutan.github.io/page5/)
## 실행 환경
 - OS: 
 - Browser:

**Comment by riyenas0925** [comment]
#167 참고

## 발생
```
SpringSecurityConfig  -> authProvider -> customUserDetailsService
          ↖    ←    ←    passwordEncoder  ←    ←      ↙
```
순환 참조 오류 발생

## 원인
원인은 SecurityConfig에서 정의한 PasswordEncoder Bean을 위에 클래스(CustomUserDetailsService, CustomAuthenticationProvider)에서도 사용하고 있어서 순환 참조 오류 발생

## 해결 방안
생성자를 이용한 생성 방식으로 변경후 PasswordEncoder를 설정한 Bean을 다른 설정 파일로 이동
