### ISSUE TITLE
[ENH] notice 페이지 디자인

### ISSUE THREAD

**Issue by 2kyung19** [riyenas0925/Sejong_Track_Management#171]
![image](https://user-images.githubusercontent.com/32586712/76681912-e4bdc600-663a-11ea-8cc4-5856683807cc.png)

일단 공지사항 페이지 따로 만들고
홈에서는 최근 공지만 카드로 띄우는게 나을꺼같

**Comment by riyenas0925** [comment]
@2kyung19 

> 일단 공지사항 페이지 따로 만들고
> 홈에서는 최근 공지만 카드로 띄우는게 나을꺼같

ㅇㅎㅇㅎ  그게 더 좋을것 같네

**Comment by 2kyung19** [comment]
@riyenas0925 
## 20200315
* list가져오는거까진 완료
> 이것만하고 와우 약초 캐러 갔슴다^^,,,,,,

![image](https://user-images.githubusercontent.com/32586712/76702774-da213080-670f-11ea-8f41-9c71a364aa31.png)

![녹화_2020_03_15_22_56_08_782](https://user-images.githubusercontent.com/32586712/76702817-3b490400-6710-11ea-8a1e-ecbbb289b87b.gif)

- [x] 글 쓰기 부분 modal
- [x] 글 수정 modal
- [x] 글 삭제 연결
- [x] date 년월일까지만 자르기

## 궁금
저 버튼 tab들이 argon에 따로 구현된게 없어서 그냥 대충 만들어서 썼는데
그래서그런지 밑부분에 효과 주기 위해 설정한 css와 js 코드가 엄청 긺
나중에 따로 css파일이랑 js파일로 만들어서 묶는게 나을까?

**Comment by 2kyung19** [comment]
@riyenas0925 @kimhanui 
## 20200316
notice 완료

* create : modal
* delete : button
* update : page

### [학생 입장]
![image](https://user-images.githubusercontent.com/32586712/76776923-bf6fba00-67ea-11ea-8c53-7f5cd91621cc.png)
### [관리자 입장]
![녹화_2020_03_17_00_52_20_818](https://user-images.githubusercontent.com/32586712/76776964-d2828a00-67ea-11ea-8d40-2b0f8ec18e1c.gif)

---
컨펌 받은 뒤 괜찮으면 
pr올리면서 url 요청 정리해서 올리겠습니당

**Comment by 2kyung19** [comment]
## + 옆에 사이드바 반응 없길래 수정
![녹화_2020_03_17_01_35_20_685](https://user-images.githubusercontent.com/32586712/76779999-a3bae280-67ef-11ea-9f89-1edab75d91c1.gif)

**Comment by kimhanui** [comment]
@2kyung19
역시 디자인이 들어가니까 편-안 합니다^^b(누더기입다가 정장걸친느낌)

Css랑 js를 같이 묶는지,따로 묶는진는 모르갯지만 :sob: 파일 따로 만들어서 묶어주거나 원래 잇는 파일에 합칠수 잇으면 좋을듯ㅇㅇ

**Comment by riyenas0925** [comment]
@2kyung19 와 진짜 웹은 디자인이다 ㅋㅋㅋㅋ
