### ISSUE TITLE
[DOC] 트랙 판정 테스트 케이스

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#195]
@kimhanui 전에 말했던 트랙 판정(25, 50, 75, 100) 테스트 케이스들 여기에 올려서 공유해주라, 판정 결과도 알려주면 감사감사

> 엑셀 파일도 코멘트에 드래그 앤 드랍으로 공유할수 있음

**Comment by riyenas0925** [comment]
@kimhanui 여기다 엑셀 파일공유 가능한가?

**Comment by kimhanui** [comment]
@riyenas0925 
근데 혹시 파일 올릴때마다 웹 캐시사용량 증가...이런 현상 있나?   
내가 캡쳐는 못햇는데 테스트로 파일 올리니까 웹 메모리부족? 이런 경고창 떳엇음
+ 파일올리고 결과보고 <뒤로가기> 하면 파일 다시 올려도 테두리가 초록색으로 안변하던데 이거 템플릿 적용해도 프론트 로직 함 확인해야할듯

**Comment by kimhanui** [comment]
> @kimhanui 여기다 엑셀 파일공유 가능한가?

@riyenas0925 
음 xlsx는 올릴 수 있는데 판정할땐 xls만 돼서 한번 확장자 바꿔줘야댐

**Comment by riyenas0925** [comment]
@kimhanui  아 파일 자체를 List<Course>로 변환해서 세션에 저장하는 방식인데 이것때문에 오류가 나는건가..? 이건 다른 방법을 찾아봐야 겠네 오류날때 처음에는 괜찮다가 나중에 난거야 아니면 처음부터 오류 난거야?

**Comment by riyenas0925** [comment]
@kimhanui 테스트 엑셀로 트랙 판정했을때 색상 코드값하고 퍼센트 잘 나오는지 알려주라

**Comment by kimhanui** [comment]
> @kimhanui 아 파일 자체를 List로 변환해서 세션에 저장하는 방식인데 이것때문에 오류가 나는건가..? 이건 다른 방법을 찾아봐야 겠네 오류날때 처음에는 괜찮다가 나중에 난거야 아니면 처음부터 오류 난거야?

처음엔 괜찮다가 나중에 오류.

이것때문인진 모르겟는데 '그'경고창 뜨고나서 다시 올리고 돌리려니까 브라우저 마비되고 컴터 마비돼서 껏다 킴 ㄷㄷ
@riyenas0925

**Comment by kimhanui** [comment]
[기이수성적_50%.xlsx](https://github.com/riyenas0925/Sejong_Track_Management/files/4387490/_50.xlsx)
[기이수성적_0%.xlsx](https://github.com/riyenas0925/Sejong_Track_Management/files/4387491/_0.xlsx)
[기이수성적_25%(down).xlsx](https://github.com/riyenas0925/Sejong_Track_Management/files/4387493/_25.down.xlsx)
[기이수성적_25%(up).xlsx](https://github.com/riyenas0925/Sejong_Track_Management/files/4387494/_25.up.xlsx)
[기이수성적_25%.xlsx](https://github.com/riyenas0925/Sejong_Track_Management/files/4387495/_25.xlsx)

@riyenas0925 동민아 데이터 조작 이렇게 해보라는거 맞음??? 함 봐주라  
25% up, down은 데이터 30개 중 25%면 7.5이라 7(down)인거랑 8(up)인걸로 나눠봄

`+` 결과는 0,25,50 다 논패 뜨네(?)
```
{
   "percent":0,
   "totalCourseCredit":0,
   "totalRuleCredit":0,
   "percentColor":"#f5365c",
   "trackJudge":{
      "BASIC":{
         "PASS":{
            "sumCredit":0,
            "ruleCredit":0,
            "minSumAndRuleCredit":0,
            "percent":0,
            "courses":[

            ]
         },
         "NON_PASS":{
            "sumCredit":9,
            "ruleCredit":9,
            "minSumAndRuleCredit":9,
            "percent":100,
            "courses":[
               {
                  "courseNo":"000001",
                  "title":"선형대수및프로그래밍",
                  "completionType":null,
                  "selectedArea":null,
                  "credit":3
               },
               {
                  "courseNo":"000002",
                  "title":"컴퓨터그래픽스",
                  "completionType":null,
                  "selectedArea":null,
                  "credit":3
               },
               {
                  "courseNo":"000003",
                  "title":"웹프로그래밍",
                  "completionType":null,
                  "selectedArea":null,
                  "credit":3
               }
            ]
         }
      },
      "APPLIED":{
         "PASS":{
            "sumCredit":0,
            "ruleCredit":0,
            "minSumAndRuleCredit":0,
            "percent":0,
            "courses":[

            ]
         },
         "NON_PASS":{
            "sumCredit":21,
            "ruleCredit":18,
            "minSumAndRuleCredit":18,
            "percent":100,
            "courses":[
               {
                  "courseNo":"000004",
                  "title":"영상처리",
                  "completionType":null,
                  "selectedArea":null,
                  "credit":3
               },
               {
                  "courseNo":"000005",
                  "title":"HCI개론",
                  "completionType":null,
                  "selectedArea":null,
                  "credit":3
               },
               {
                  "courseNo":"000006",
                  "title":"웹프로그래밍설계",
                  "completionType":null,
                  "selectedArea":null,
                  "credit":3
               },
               {
                  "courseNo":"000007",
                  "title":"웹기반시스템",
                  "completionType":null,
                  "selectedArea":null,
                  "credit":3
               },
               {
                  "courseNo":"000008",
                  "title":"윈도우즈프로그래밍",
                  "completionType":null,
                  "selectedArea":null,
                  "credit":3
               },
               {
                  "courseNo":"000009",
                  "title":"XML 프로그래밍",
                  "completionType":null,
                  "selectedArea":null,
                  "credit":3
               },
               {
                  "courseNo":"000010",
                  "title":"데이터컴퓨팅",
                  "completionType":null,
                  "selectedArea":null,
                  "credit":3
               }
            ]
         }
      }
   }
}
```

**Comment by riyenas0925** [comment]
@kimhanui 지금 한번 테스트 해보려니까 xlsx 여서 오류가 나네;;;  riyenas0925@gmail.com 여기로 엑셀 파일 보내줄수 있어??

**Comment by riyenas0925** [comment]
@kimhanui 아그리고 기이수 성적 파일의 학수 번호는 숫자가 아니라 문자열이 여서 숫자 앞에 ' 이거 붙여서 해야하는데 이렇게 했어??

00001 (X) -> '00001 (O)

**Comment by kimhanui** [comment]
> @kimhanui 아그리고 기이수 성적 파일의 학수 번호는 숫자가 아니라 문자열이 여서 숫자 앞에 ' 이거 붙여서 해야하는데 이렇게 했어??
> 
> 00001 (X) -> '00001 (O)

ㅇㅎㅇㅎ 그렇게 안하고 셀속성을 텍스로 설정하긴했는데 오류는 안낫음 @riyenas0925

**Comment by riyenas0925** [comment]
@kimhanui 그럼 위에 처럼 해보고 한번 돌려보실?

**Comment by kimhanui** [comment]
@riyenas0925 
![image](https://user-images.githubusercontent.com/30483337/77657705-02831780-6fb9-11ea-93b4-d1921c2c05c4.png)
그래 이거엿음ㄷㄷ

**Comment by riyenas0925** [comment]
@kimhanui 엥 저거 뭐지.... 지금 일단 업로드 하면 업로드 한 파일을 세션에서 삭제할 메서드를 안만들긴 했는데 이것 때문인가? 계속 데이터가 쌓여서 공간이 없는거지

**Comment by kimhanui** [comment]
![image](https://user-images.githubusercontent.com/30483337/77658991-d7012c80-6fba-11ea-8d7b-c9e223fe4942.png)

@riyenas0925  ㅇㅇ그런듯 기록 지우면 다시 문제 없음.

그 엑셀에 `'003001`이런식으로 하니까 오히려 데이터 출력이 안되네

**Comment by riyenas0925** [comment]
@kimhanui 데이터 출력이 안된다는 뜻이 에러 난다는겨??

**Comment by kimhanui** [comment]
@riyenas0925 ㄴㄴ 에러는 없는데 json자체가 아무것도 안나타남.

그리고 인터넷 사용기록 삭제는 ㄹㅇ그냥 임시방편인듯  
다시 두 번정도 더  올리니까 경고창 다시뜸ㄷ

**Comment by riyenas0925** [comment]
@kimhanui 이거 빨리 수정해야겠네;;; 판정 부분도 equals 부분이 잘못된것 같은데 이것도 수정해서 내일까지 올릴께

**Comment by kimhanui** [comment]
@riyenas0925 부탁함ㅇㅇ 글고 메일로 일단 `'`안 붙인 xls파일들 보내놧음

**Comment by kimhanui** [comment]
### 간이 테스트(정말 `'`붙인 파일이어서 json이 안뜨는가?)
`'`붙인 파일(위에서 `'0003001`식으로 하라 했던거)을 `foo파일`이라 할게


서버 처음 열리고 나서 foo파일 돌려봣을 땐 json안뜸. 근데 다른 파일들 넣다가 (중간에 경고창 떠도 강행했는데) 다시 넣어보니 뜸.  

- 파일 몇번 돌려봐야 foo파일도 읽히나싶어서 서버 재부팅하고 foo파일만 5번 연속으로 돌려봄
  > json 안뜸

- 다른 파일들 넣다가 `foo`넣어야 작동하나싶어서 50%, 100%, 다시`foo`, 25%, 다시`foo`순으로 넣어봄(이 때 경고 무시)
  > json 안 뜸

-  데이터 가공한 파일들 말고 처음 다운받은 `순수한 상태인 파일`넣고 돌려봄. 잘됨. 이후 `가공한 파일들` 다시 넣어봄
   >  `순수한 상태인 파일`의 결과가 계속 똑같이 출력됨.

#### 참고
 메모리성 경고는 쓰던 브라우저 닫고 새로운 브라우저에서 작업하면 ㄱㅊ한 것 같음. 경고 뜨면 새 브라우저 만들고... 또 뜨면 또 만들고...


### 여기까지 결론 
- `'`붙인거라 안 뜨는게 아님.
- 어떤 이유에서인지 `가공된 파일들`은 읽지 못하지만 `순수한 파일`은 읽을 수 있다.
- `가공된 파일`은 `순수한 파일` 후 읽을 수 있음(인식) but 한번 인식되면 똑같은 데이터만 긁어 옴  --> 세션 문제인 것 같다. 

### 정리 
위에서 말한대로 파일 다시 넣을 때 세션에서 이전 파일기록 삭제 해주심댈듯. @riyenas0925

**Comment by riyenas0925** [comment]
@kimhanui 
어가공된 파일은 순수한 파일 후 읽을 수 있음(인식) but 한번 인식되면 똑같은 데이터만 긁어 옴 --> 세션 문제인 것 같다. -> 이거는지금 세션이 삭제되지 않기 때문에 처음 인식한 순수한 파일이 계속 읽히는 걸꺼임

**Comment by riyenas0925** [comment]
@kimhanui 지금 메일 안온것 같은데 다시 보내줄수 있음?? riyenas0925@gmail.com

**Comment by riyenas0925** [comment]
@kimhanui 아 그리고 파일 수정할때 microsoft excel 사용해서 한거야?

**Comment by kimhanui** [comment]
@riyenas0925 지금 다시 보낼게 마소오피스 씀 ㅇㅇ

**Comment by riyenas0925** [comment]
@kimhanui 음... 나도 학교에서 주는 office 365 설치해서 수정해봤는데 내꺼는 잘 수정되는것 같은데 다른이름으로 저장한거야? 아니면 그냥 다운받은 파일 수정해서 저장한거야?

**Comment by kimhanui** [comment]
@riyenas0925 ㅇㅎ?? 다운받은 파일 수정해서 저장함요 너가 해봣을 때 판정 잘 된다는거지?

**Comment by riyenas0925** [comment]
@riyenas0925 ㅇㅇ 조금 수정해서 했을때는 잘 되더라고 너가 파일 보내주면 너껄로 함 해볼라고

**Comment by riyenas0925** [comment]
@kimhanui 해봤는데 뭔가 저장이 잘못된것 같은데?? 엑셀에서 지원하지 않는 서식이라고 오류 뱉어내는데 usi에서 다운받고 숫자 변경할때 '00001 이렇게 하나만 변경한다음에 첨부해봐바

우선 버그 픽스한거 pr 올렸으니까 어프로브 하고 테스트 해보면 될것 같은데 그리고 data.sql도 조금 달라져서 학수번호 조금 수정해야할것 같음

**Comment by kimhanui** [comment]
@riyenas0925 오 내가 잘못저장한게 맞는것같음 `'`랑 셀 서식 설정하는거랑 다른가?일단 아직 시도를 한번밖에 안해봐서 이수율 달라진거 딱 한번 확인햇는데  

컴 또 다운됨(?) <- pr올린거 풀 받은 상태
그냥 내 컴의 문젠가싶기도하다?

**Comment by kimhanui** [comment]
## 예상이랑 percent값 다른것도 잇으니 잘 보삼
엑셀파일은 메일 보냄.
> 100


![image](https://user-images.githubusercontent.com/30483337/77769760-9b806400-7087-11ea-88fe-724549e15ce4.png)
> 25


![image](https://user-images.githubusercontent.com/30483337/77769785-a63af900-7087-11ea-8c99-c60f8e436af1.png)
> 25 down


![image](https://user-images.githubusercontent.com/30483337/77769906-d2ef1080-7087-11ea-946e-5d563a13e28d.png)
> 50


![image](https://user-images.githubusercontent.com/30483337/77770014-f1550c00-7087-11ea-8acc-f8bbf18967c4.png)
> 0

![image](https://user-images.githubusercontent.com/30483337/77770230-47c24a80-7088-11ea-8ae5-cf702ae9470b.png)

**Comment by riyenas0925** [comment]
@kimhanui 뭔가 예상과 다른 거는 내가 트랙과목 전에는 순서대로 넣었는데 이번에 실제 데이터로 바꿔서 그런건가??? 한번 이거 확인해서 해보실?

**Comment by kimhanui** [comment]
## 테스트 다시
85개 학수번호 넣음. @riyenas0925 

[트랙테스트.zip](https://github.com/riyenas0925/Sejong_Track_Management/files/4396652/default.zip)

> 0

![image](https://user-images.githubusercontent.com/30483337/77815251-8d205f80-70fc-11ea-9be6-40b2a7e8bed5.png)


> 25

![image](https://user-images.githubusercontent.com/30483337/77815260-a32e2000-70fc-11ea-9583-ab4866eeef1c.png)


> 50


![image](https://user-images.githubusercontent.com/30483337/77815269-b3de9600-70fc-11ea-8e29-991e0c4e4bcb.png)


> 100

![image](https://user-images.githubusercontent.com/30483337/77815278-c9ec5680-70fc-11ea-9c69-77e0e261a4cb.png)

**Comment by kimhanui** [comment]
## 테스트 다시 3
HCI기준 @riyenas0925 
동민아 혹시 내가 직접 교과목명, 이수구분, 이런거 바꿔줘야 하는거니?
![image](https://user-images.githubusercontent.com/30483337/77817587-51db5c00-710f-11ea-89b5-2770718dfdc6.png)

> 25

![image](https://user-images.githubusercontent.com/30483337/77817484-75ea6d80-710e-11ea-90e5-bdfc2f48e610.png)

>  50

![image](https://user-images.githubusercontent.com/30483337/77817509-b6e28200-710e-11ea-9751-e0eec3f46e2a.png)

> 100

![image](https://user-images.githubusercontent.com/30483337/77817538-ef825b80-710e-11ea-9cad-cf2772b95993.png)
