### ISSUE TITLE
[ENH] 학생들의 트랙 판정 기록 저장 기능

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#213]
@kimhanui 해보고 궁금한 내용있으면 코멘트 달아주십셔

* TrackJudge Entity로 변경하여 학생들이 트랙 판정 조회를 할때 DB에 저장
* 처음 홈화면에서 가장 최근에 조회한 트랙 판정 결과 표시

**Comment by kimhanui** [comment]
## issue및 to-do정리
- [x] cascadetype 방향 (mem, track모두 log쪽으로)
- [x] 연관관계 : mem-log(1:N), log-track(N:1)  (식별자 클래스x)
- [x] 서비스 : 학생기준, 트랙기준, 전체를 조회(desc)
- [x] querydsl 쓰기

**Comment by kimhanui** [comment]
## Question
### 1. tx 적용 범위
`updateOrInsert()`메소드에서 tx을 선언하지 않아도 된다고 생각했다.  
굳이 선언하지 않아도 내부에서 호출된 메소드가 tx을 쓰기 때문이다.  
그런데 실제로는 `updateOrInsert()`에 tx을 선언해야만 내부에서 변경된 데이터들이 db에 반영됐다. 
**이유는?** 
![image](https://user-images.githubusercontent.com/30483337/79049437-ac6fce80-7c5e-11ea-96c6-0191ae0a4f98.png)

### 2. 트랙 판정 pnp @riyenas0925 
`APITrackJudgeController`에서 트랙을 판정 서비스를 이용하고나면 pnp여부를 알 수 있을것이라 생각했다.   
하지만 **판정 후 `TrackStatistic`을 반환하는데 속성에 `Map`을 이용해 뭔가 분류가 많이 돼있었고 어느 부분에서 pnp을 읽어야할지 모르겠다.**
![image](https://user-images.githubusercontent.com/30483337/79049554-46377b80-7c5f-11ea-972c-6a8bd55caeab.png)

**Comment by kimhanui** [comment]
@riyenas0925 
 판정 service에 delete 메서드가 필요할까?
