### ISSUE TITLE
[CLN] cleaning service of track

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#214]
![image](https://user-images.githubusercontent.com/30483337/78169680-bd655680-748c-11ea-99a2-07f2fbe44c96.png)
각 서비스 클래스 평균 40줄 정도임 하나로 합치는게? @riyenas0925

**Comment by riyenas0925** [comment]
@riyenas0925 음.... 뭔가 한 클래스에 여러 책임을 주는것보다 한클래스에 하나의 책임을 주는게 좋을것 같아서
## 참고
https://github.com/riyenas0925/Design_Pattern/blob/master/Single%20Responsibility%20Principle.md
