### ISSUE TITLE
[DOC] UIS에서 소속 및 학년이 어떻게 뜨는지 알려달라!

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#217]
@kimhanui @2kyung19 uis 상에서 소속 대학과 학과를 가져오려고 하는데 다른 학과는 어떻게 되어 있는지 확인해봐야 할것 같아서 이거 보면 바로 캡처해서 여기에 올려주시면 감사하겠습니다.

![image](https://user-images.githubusercontent.com/32615702/78451117-7eb6e280-76be-11ea-9b2d-f2fea9fe0a0c.png)

**Comment by kimhanui** [comment]
@riyenas0925 Here
![image](https://user-images.githubusercontent.com/30483337/78498048-64940780-7785-11ea-87c3-97ce2d0b4ba8.png)
