### ISSUE TITLE
[BUG] 내정보 페이지 수정 변경

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#219]
![image](https://user-images.githubusercontent.com/32615702/78452330-ad848700-76c5-11ea-8f29-a134db4bd318.png)

@2kyung19  
* 좌측 정보랑 우측 정보가 세션에 저장되있는 값을 가져오는게 아니라 임의의 값으로 설정해서 다른 오류 발생
* 좌측 정보에서 학번이 아이디이기 때문에 학번이나 아이디 부분 삭제 필요

**Comment by 2kyung19** [comment]
우측정보에 대학이랑 학과명은 가져오는 값 임의로 넣어논거 나중에 서버에서 정보 저장 업데이트되면
저기다가 넣으면되여
