### ISSUE TITLE
[BUG] 전체 트랙 페이지 수정

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#220]
@2kyung19 
![image](https://user-images.githubusercontent.com/32615702/78452429-31d70a00-76c6-11ea-83ff-2d8b8380b383.png)
이부분 api에서 받아오는 방식이 아니라 html에서 정의한 방식이여서 무인기 트랙이 보이지 않는 오류

위에 오류 해결해보면 알겠지만 무인기 같은경우는 기초, 응용, 산학, 공통 이렇게  4가지이기 때문에 한눈에 안보이는 오류가 발생.... 

이거 화면 크기에 맞게 과목을 자동으로 줄바꿈을 해서 한눈에 보일수 있게 해줘야 할것 같은데 어떻게 생각함??

**Comment by 2kyung19** [comment]
@riyenas0925 
* 아 오키 저부분아마 api에서 긁어온게아니라서 오류나는게 맞을꺼야 수정할께

* 전체트랙 부분 지금 맘에 안들어가지구 계속생각하고있긴한데
한눈에 보여야하는데 보여줘야할 정보가 많아서 씁....일단 자동줄바꿈까지 수정해볼께
