### ISSUE TITLE
[Question] 이것, 클래스명이랑 인스턴스이름이랑 조금 다른느낌인 !

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#227]
![image](https://user-images.githubusercontent.com/30483337/78506520-f36c4880-77b4-11ea-842b-e502d0522ed5.png)

@riyenas0925 잘 몰라서 그러는데 이거 잘못쓴거 아니지..?

**Comment by riyenas0925** [comment]
@kimhanui 정답.... subject였다가 내가 course가 더 맞는것 같아서 변경했는데 변수는 수정이 안된것 같음 ㅋㅋ

**Comment by kimhanui** [comment]
@riyenas0925 아ㅋㅋ 오키 나중에 코드 pr올릴때 같이 수정해주라
