### ISSUE TITLE
[Bug?] 트랙 학위 설정 덜 됨

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#230]
트랙 판정중 1,2,10(사이버국방)빼고 학위 설정안됨. 아래는 학위 설정안된 상태에서 판정하려고하면 나타나는 로그

![image](https://user-images.githubusercontent.com/30483337/79050134-f0fd6900-7c62-11ea-8164-5cdc98e6ce47.png)
![image](https://user-images.githubusercontent.com/30483337/79050107-c01d3400-7c62-11ea-8e91-45c6f690c421.png)

**Comment by riyenas0925** [comment]
@kimhanui 버그는 아니고 아직 data.sql에 트랙정보를 1, 2, 10만 넣어서 그런거임 ㅇㅇ
