### ISSUE TITLE
[ENH-Front]

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#241]
![image](https://user-images.githubusercontent.com/30483337/82112370-38f23d00-9787-11ea-808c-8cdc58acaa39.png)
인증되었다는 알림뜨기 전까지 3~4초정도 걸림. 학번 input 밑에 `동그라미 로딩` 같은거 넣으면 어떨까요? 호호 호

**Comment by kimhanui** [comment]
@2kyung19 @riyenas0925

**Comment by riyenas0925** [comment]
@kimhanui @2kyung19 오 좋다 로딩 될때는 백그라운드 클릭 못하게도 부탁드림다~

**Comment by riyenas0925** [comment]
@kimhanui @2kyung19 이제 uis 인증 응답에 학과와 대학도 반환되니까 이것도 자동으로 채워지게 부탁드림다
![image](https://user-images.githubusercontent.com/32615702/82113275-c5a0f900-978f-11ea-970b-14899127044b.png)

**Comment by 2kyung19** [comment]
- [x] 회원가입 필드 수정
- [x] 마이페이지 필드 수정
- [x] 전체트랙보기 select univ 서버에서 데이터가져오기
- [x] 트랙현황조회에서 전체트랙조회 api 반영
- [x] 전체트랙조회에서 페이지 이동 없이 바로 다른 트랙 결과 출력
- [ ] 회원가입,트랙조회 시 로딩창
- [x] 메인페이지 변경
- [x] 페이지 아이콘
---
#### 할일 더 추가바랍니다.
