### ISSUE TITLE
로그인기능 구현 중(2개)

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#54]
- [x]  jsp에서( joinView.jsp, joinResult.jsp, loginView.jsp 중에 있음) jquery 쓰려고 임의로 <link> 넣었는데 혹시 이미 있는 파일을 include해서 해결되는거라면 알려주시거나 코드 리팩토링 좀 부탁
- [x] Member의 id가 Long인 이유는 학번이기 때문임?? 아니면 대체키를 사용하기 위함인가?? **임의로 String으로 바꿔버렸으니 피드백 꼮 부탁**

**Comment by kimhanui** [comment]
화면 캡쳐 첨부 @riyenas0925 
### 회원가입
![image](https://user-images.githubusercontent.com/30483337/67868905-f6ad3980-fb6f-11e9-8782-3de08d541212.png)

### 로그인
![image](https://user-images.githubusercontent.com/30483337/67868958-09c00980-fb70-11e9-8be4-741699b0a48b.png)

### 로그아웃
(로그아웃 페이지랄게 없음)  
로그인 후
![image](https://user-images.githubusercontent.com/30483337/67868985-16dcf880-fb70-11e9-98d6-2b22faafca04.png)

로그아웃 눌렀을 때  
![image](https://user-images.githubusercontent.com/30483337/67869024-278d6e80-fb70-11e9-8e03-a8d9a14457a5.png)

**Comment by riyenas0925** [comment]
@kimhanui  adminlte로 적용해서 pr 부탁~
회원가입 https://adminlte.io/themes/AdminLTE/pages/examples/register.html
로그인 https://adminlte.io/themes/AdminLTE/pages/examples/login.html

그리고 js, css 같은경우는 views/include 안에 있는 파일들처럼 나눠서 include 해서 사용하고 있어서 사용하려면 `<%@ include file="include/head.jsp" %>` 이렇게 include 해주면 될꺼야

**Comment by riyenas0925** [comment]
@kimhanui 
- [ ] Spring Security, java config 방식으로 변경

member -> 멤버 table
memberrole -> 멤버 권한 table
