### ISSUE TITLE
문서화 방법 정하기

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#65]
- [x] 문서화는 어디에 어떻게? (wiki?, gitbook? ..?)
- [x] 코딩컨벤션 정하기
- [x] ReadMe.md 수정하기
- [x] 라이센스는 어떤걸로?

@kimhanui @2kyung19

**Comment by riyenas0925** [comment]
https://www.slideshare.net/deview/5-d2-campus-fest-ot-87095906

**Comment by kimhanui** [comment]
1. 
- where : 일단 wiki에 햇으면 좋겟음. 
- how : 비슷한건 시리즈로 묶고( ex- [java]~~ 처럼 [ ]로 ), 제목에 작성자 표시
2. 코딩컨벤션 - 너무 방대한데 보기 불편한 구조가 있었다면 그걸 제시하고 하나씩 추가해가는건 어떰
3. ReadMe.md - ?
4. 라이센스 - 
![image](https://user-images.githubusercontent.com/30483337/68032406-fd1eeb00-fd00-11e9-978b-a95a36925349.png)
일단 Apache  

➕ 근데 이거 private으로 돌려야하지 않나?

**Comment by riyenas0925** [comment]
@kimhanui 
그럼 컨벤션이나 문서는 위키로 작성하고 라이센스는 Apache로 하자

private는 누가 볼거라고 생각 안해서 안한거긴 한데 이것도 고민해봐야겠네
