### ISSUE TITLE
adminLTE적용

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#75]
### 할 것
- [x] 회원가입,로그인페이지에 적용   
- [ ] 일부파일(home.jsp, exception.jsp)에 body, div 여는 태그가 없음 
 
### 주의
 .gitignore는 건들이지 않는다

### Suggest
로그인,회원가입 페이지에 <link>되는 파일이 다 head.jsp에 속해잇음

그부분만 묶어서 따로 파일 만들고 - > head-basic.jsp,   
head.jsp는 head-basic.jsp를 include  
로그인,회원가입 페이지 : head-basic.jsp를 include   
기존 페이지들 : 그대로 head.jsp를 include
이렇게 하는건 어떰? @riyenas0925

**Comment by riyenas0925** [comment]
@kimhanui suggest는 그렇게 해도 좋을것 같네 이름을 head.jsp 하고 head-color.jsp 이렇게 해서 이파일이 색상에 관련된 파일이라는걸 알려주는건 어때??

**Comment by riyenas0925** [comment]
head.jsp (색상  div 가 없는 일반적인  head 태그)
head-color.jsp (head.jsp include + 색상 div 포함)

로그인, 로그아웃 -> head.jsp include
홈, 전체 트랙, 트랙 업로드, 트랙 결과 -> head-color.jsp include

**Comment by kimhanui** [comment]
ㅇㅋㅇㅋ 반영해서 pr 올려보겟음

**Comment by riyenas0925** [comment]
@kimhanui 
나중에 https://www.eclipse.org/che/ 이거 한번 사용해봐 이클립스에서 만든 웹 ide 인데 스프링 부트용으로 구름  ide 보다 좋은것 같음ㅇㅇ
