### ISSUE TITLE
FetchType (in 'Rule.java')

### ISSUE THREAD

**Issue by kimhanui** [riyenas0925/Sejong_Track_Management#93]
![image](https://user-images.githubusercontent.com/30483337/69357307-34f9cc80-0cc8-11ea-92fb-af38fea66ee4.png)
페치타입을 ```@ManyToOne```인데 LAZY로 한 이유가 따로 있음?

**Comment by riyenas0925** [comment]
fetch전략을 LAZY로 하고 필요한 부분만 EAGER로 바꾸는 방법이 좋을 것같아서 EAGER로 하면 연관된 엔티티 전부를 가져오느라 느려질것 같아서 그렇게 했음 ㅇㅇ
참고 : https://yellowh.tistory.com/126

**Comment by kimhanui** [comment]
아 ㅇㅇ EAGER는 개발 완료단계쯤에 정하는게 좋다하는구나 ㅇㅋㅇㅋ
