### ISSUE TITLE
[ENH] 과목 추가 기능 구현

### ISSUE THREAD

**Issue by riyenas0925** [riyenas0925/Sejong_Track_Management#98]
uis 시스템에있는 과목을 일일이 추가하기에는 불가능 함.... 학기별로 열리는 강의의 전체 목록을 엑셀파일로 제공하기 때문에 엑셀파일을 첨부하여 tbl_subject의 데이터를 채울수 있는 기능이 필요함

- [ ] 엑셀 파일 첨부하여 전체 과목 데이터를 저장할수 있는 기능 필요
- [ ] 과목이 중복시 판별(이름과 학수번호 학점 등등...)을 통해 최신 데이터만 남기고 삭제

**Comment by riyenas0925** [comment]
@2kyung19 우선 이기능 먼저 하자 


먼저 데이터 베이스는 아래와 같이 구성 될것 같고

```
강의시간표 테이블              --  1:N  --          과목 테이블
1 | 2019 1학기 강의시간표                            1 | 1 | 선대
2 | 2019 2학기 강의시간표                            2 | 1 | 물리
                                                    3 | 1 | 화학1
                                                    4 | 2 | 화학2
                                                    5 | 2 | 물리2
```     
우선적으로 보여줘야 할부분이 강의시간표 테이블에 저장되어있는 강의시간표 엑셀 파일 이름 목록을 출력해야 하고, 강의 시간표 이름을 눌렀을때 그 강의 시간표에 해당하는 과목이 표시할수 있는 부분이 하나 있어야 할것 같음 그다음에 새로운 강의 시간표를 첨부할 공간 까지 이렇게 3가지가 필요함 

월요일 22시까지 ppt나 이런걸로 한번 디자인해서 보여줄수 있나?
아래에 코멘트로 달아주라

## 작동흐름
2019 1학기 강의시간표 첨부 -> 강의시간표 테이블에 강의시간표 엑셀 이름이 저장됨 -> 강의 시간표 테이블의 외래키를 이용하여 과목테이블에 강의시간표안에 있는 과목들이 저장됨

**Comment by 2kyung19** [comment]
@riyenas0925 관리자용 강의시간표 업로드 페이지 맞는건가?

![image](https://user-images.githubusercontent.com/32586712/73626013-a1128c80-468a-11ea-8102-c91ae309d1e3.png)
대충 레이아웃만,, 저기서 `강의시간표 추가` 버튼 누르면  


![image](https://user-images.githubusercontent.com/32586712/73626120-1da56b00-468b-11ea-972d-89ee47557620.png)
drag and drop 탭이 밑으로 내려오는 식

### 참고
https://demos.creative-tim.com/argon-dashboard/index.html
이 부트스트랩 템플릿으로 갈 듯 귀엽고 깜찍하고 깔끔한게 아주 맴에든다
(https://github.com/creativetimofficial/argon-dashboard  : MIT 라이센스)

**Comment by riyenas0925** [comment]
@2kyung19 오오 깔끔하게 잘했네 굿굿
아 그리고 위에 디자인은 가로보다 세로가 긴데 관리자 페이지 같은경우는 pc 모니터로 사용할것 같아서 세로보다 가로가 긴게 더 좋을것 같은데 어떰??

**Comment by riyenas0925** [comment]
@2kyung19 
음 그리고 새로운 템플릿 같은경우는 지금 adminLTE 템플릿을 사용중이여서 만약 변경하려면 우선 위에꺼 추가하고 두개의 템플릿이 있는 상태해서 천천히 한 템플릿으로 전환해야 할것 같음

**Comment by kimhanui** [comment]
> @2kyung19 오오 깔끔하게 잘했네 굿굿
> 아 그리고 위에 디자인은 가로보다 세로가 긴데 관리자 페이지 같은경우는 pc 모니터로 사용할것 같아서 세로보다 가로가 긴게 더 좋을것 같은데 어떰??

어디 부분 말하는거임?? 어디가 가로보다 세로가 더 김? @riyenas0925

**Comment by riyenas0925** [comment]
@2kyung19 
음 그리고 새로운 템플릿 같은경우는 지금 adminLTE 템플릿을 사용중이여서 만약 변경하려면 우선 위에꺼 추가하고 두개의 템플릿이 있는 상태해서 천천히 한 템플릿으로 전환해야 할것 같음

**Comment by riyenas0925** [comment]
@kimhanui 위에 보면 전체 레이아웃이 세로가 긴 직사각형 형태자너 뭔가 관리자 기능은 pc 모니터에 맞춰서 가로로 긴 직사각형 형태가 조금더 편하지 않나 싶어서

**Comment by 2kyung19** [comment]
@riyenas0925 @kimhanui 
아 저부분은 그냥 메인 컨텐츠 부분이고
아마 사이드바랑 헤더 nav 적용 다 되면
![image](https://user-images.githubusercontent.com/32586712/73642225-a5ec3600-46b4-11ea-88f7-3726c1741067.png)
대충 이런 모양 나올꺼 같은데 더 가로로 늘릴까?

**Comment by riyenas0925** [comment]
@2kyung19 ㅇㅎㅇㅎ 생각보다 빈부분이 많을줄 알았는데 괜찮네 이대로 진행해도 될것 같음~

그리고 위에 템플릿 관련해서 어떻게 할지 알려주라

**Comment by 2kyung19** [comment]
@riyenas0925 밥묵고다시올께

**Comment by 2kyung19** [comment]
@riyenas0925

템플릿은 따로 이슈 하나 올릴께

### 질문
* 굳이 과목 table이 필요할까?
중복제거한다고하더라도 엄청많을탠데,,

**Comment by riyenas0925** [comment]
@2kyung19 ㅇㅎㅇㅎ 과목테이블은 만약 2018년도에 a,b,c,d, 라는 과목이 있고 2019년도에는 c,d 라는 과목이 있으면 중복되는 c,d 과목은 2019년로 업데이트 되는거고 a,b 과목은 2018년도로 유지되게 하려고 이렇게 하면 중복된 과목도 방지할수 있으면서 과목의 최신년도 까지 있는지 알수 있을것 같아서

**Comment by 2kyung19** [comment]
확인~

**Comment by riyenas0925** [comment]
Subject에 필수 변수
NO
학수번호	
교과목명	
이수구분	
선택영역	
학점
